apiVersion: v1
kind: ConfigMap
metadata:
  name: oficina-config
  namespace: oficina
data:
  DB_HOST: postgres
  DB_PORT: "5432"
  DB_NAME: oficina_db
  MAIL_HOST: smtp.mailtrap.io
  MAIL_PORT: "2525"
  JPA_DDL_AUTO: update
  SHOW_SQL: "true"
  SECURITY_DISABLED: "true"
  MANAGEMENT_HEALTH_MAIL_ENABLED: "false"
  MANAGEMENT_ENDPOINT_HEALTH_SHOW_DETAILS: always
  MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: health,info
  MANAGEMENT_HEALTH_DB_ENABLED: "true"
  MANAGEMENT_ENDPOINT_HEALTH_PROBES_ENABLED: "true"
  MANAGEMENT_HEALTH_LIVENESSSTATE_ENABLED: "true"
  MANAGEMENT_HEALTH_READINESSSTATE_ENABLED: "true"
