apiVersion: v1
kind: Secret
metadata:
  name: newrelic-secret
  namespace: oficina
type: Opaque
stringData:
  license-key: "YOUR_NEW_RELIC_LICENSE_KEY_HERE"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: newrelic-config
  namespace: oficina
data:
  NEW_RELIC_ENVIRONMENT: "dev"
  NEW_RELIC_DISTRIBUTED_TRACING_ENABLED: "true"
  NEW_RELIC_LOG_LEVEL: "info"
